skinparam dpi 600
@startuml
start
:From PTM enriched & total proteome experiments
Load peptide ion identification and quantification data;
fork
  partition "site, multisite branch" {
  :Filter peptidoforms for identification FDR, and PTM localization scores;
  :Generate **multisite** and **site** identifiers;
  
  fork
    :Summarize to site level;
  fork again
    :Summarize to multisite level; 
  end fork
  }
fork again
  partition "protein branch" {
  :Filter for identification FDR;
  :Summarize to protein level;
  }
end fork

:Normalize site, multisite, and protein data;
fork
  partition "Model then correct fold changes (MSstatsPTM)" {
  :**Differential analysis**
  Model with linear models 
  site, multisite, and protein data;
  if (protein data available?) then (Yes)
    :Merge PTM & protein outputs
    to adjust PTM **fold changes**;
  else (No)
    :No adjustment;
  endif
  }
fork again
  partition "Correct abundances then model (msqrob2PTM)"{
  if (Protein data available?) then (Yes)
    :Merge PTM & protein outputs
    to adjust PTM **abundances**;
  else (No)
    :No adjustment (DPE);
  endif
  : **Differential analysis**
  Model with linear models
  multisite, site, and protein data;
  }
end fork

' Removed stray end fork here (originally line 38) to match fork count

:Output differential expression results:
 multisite (DPU/DPE), site (DPU/DPE), protein (DPE);
:Generate visualization (Volcano plots & heatmaps);
stop

@enduml
